#!/bin/sh

cd /tmp

clear

echo "Waiting for the USBSI device to be found"
while [ ! -e /dev/ttyACM0 ]; do
  sleep 1
done

ln -s /dev/ttyACM0 /dev/serial/by-id/usb-RJG_Inc._Lynx_USBSI_17LS200001-if00

/usr/bin/RTService > /dev/null &

echo "waiting for lynx sensors to be detected"
sleep 1
echo "."
sleep 1
echo "."
sleep 1

# change directory so the hardware.csv file can be found
cd /usr/bin/tools ; /usr/bin/tools/hardware_tester

echo
echo "Press enter to poweroff"

read

poweroff
