#!/bin/sh
# System initialization
#
# /sbin/init
#       |
#       +--(1) /etc/sysinit
#       |
#       L--(2) /bin/sh (main console)

dmesg -n 1

#mount -t devtmpfs none /dev
mount -t proc none /proc
mount -t tmpfs none /tmp -o mode=1777
mount -t sysfs none /sys
mkdir -p /dev/pts
mount -t devpts none /dev/pts
mkdir /dev/shm
mount -t tmpfs none /dev/shm -o mode=1777,rw,nosuid,nodev,noexec,noatime
mount -t efivarfs none /sys/firmware/efi/efivars -o rw,nosuid,nodev,noexec,noatime

mkdir /dev/serial
mkdir /dev/serial/by-id
cp -R /etc/services /tmp/

echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s

